module.exports = {
    formHead: {
        fontSize: 30, 
        color: '#013A6F', 
        textAlign: 'center', 
        fontWeight: 'bold', 
        //backgroundColor: 'white,
    }, 
    formInput: {
        width: '80%', 
        height: 40, 
        backgroundColor: 'white', 
        borderRadius: 10, 
        marginVertical: 10, 
        paddingHorizontal: 15, 
        paddingVertical: 10, 
        fontSize: 10, 
    }, 
    formbtn: {
        width: '80%', 
        backgroundColor: '#013A6F', 
        borderRadius: 10,
        borderColor: 'white', 
        borderWidth:1, 
        fontSize: 25, 
        color: 'white', 
        textAlign: 'center', 
        paddingVertical: 10, 
        marginVertical: 10,
    },
    formbtnSignup: {
        width: '80%', 
        backgroundColor: 'white', 
        borderRadius: 10,
        borderColor: 'white', 
        borderWidth: 1, 
        paddingVertical: 10, 
        marginVertical: 10,
    },
    formbtnSignupText: {
        color: '#013A6F', 
        fontSize: 25,
        textAlign: 'center', 
    },
    formbtnLoginText: {
        color: 'white', 
        fontSize: 25,
        textAlign: 'center', 
    },
    formTextLinkRight: {
        color: 'gray', 
        fontSize: 15, 
        textAlign: 'right',
        width: '80%',
        marginVertical: 10,
    },
    formTextLinkCenter: {
        color: 'grey', 
        fontSize: 16,
    },
    formHead2: {
        fontSize: 20, 
        color: 'white', 
        textAlign: 'center', 
        // fontWeight: 'bold', 
        //backgroundColor: 'white,
    },
    formHead3: {
        fontSize: 20, 
        color: 'grey', 
        textAlign: 'center', 
        fontWeight: '400',
        padding: 10,
        borderRadius: 10,
        width: '80%',
        marginVertical: 10
        // fontWeight: 'bold', 
        //backgroundColor: 'white,
    },  
}